<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
		<string>pete</string>
	</array>
	<key>name</key>
	<string>Pete Todo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#[a-zA-Z0-9]*</string>
			<key>name</key>
			<string>comment.hash.pete</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pete</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.pete</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(Every|\%)([A-Za-z0-9\-\s/,]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pete</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.startdate.pete</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pete</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.enddate.pete</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@)\s([A-Za-z0-9:\s\-/,]*)\s(-)\s([A-Za-z0-9:\s\-/,]*)\s</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pete</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.hash.reference.pete</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\^)\s?(#[A-Za-z0-9]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.reference.pete</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.operator.pete</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.increment.pete</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.other.unit.pete</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pete</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(Start|End)\s?(\-|\+)\s?([0-9]+)\s?(hours?|days?|weeks?|months?)\s?(,?)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pete_todo</string>
	<key>uuid</key>
	<string>26251B18-6B1D-12D9-AFDB-000D93589AF7</string>
</dict>
</plist>
